browser = chromium
url = https://naveenautomationlabs.com/opencart/

<<<<<<< HEAD
username =
password =
=======
username = 
password = 
>>>>>>> 13cd70737e9ff7b2000acc5561ef5aea90579df3

headless = false
