name: Playwright Java Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Install Playwright Browsers
        run: mvn exec:java -e
        continue-on-error: true

      - name: Download Maven Dependencies
        run: mvn dependency:resolve

      - name: Install Playwright Browser Dependencies
        run: |
          mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Run TestNG Suite
        run: |
          mvn test \
          -Dsurefire.suiteXmlFiles=src/test/resources/testrunners/testng_regressions.xml

      - name: Upload TestNG Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-report
          path: |
            test-output/**
            build/**
            screenshot/**
            
      - name: Upload Extent Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: build      
